---

- name: restart_nginx
  service:
    name: nginx
    state: restarted
  become: true
  notify:
    - "_notify nginx restart"

- name: "_notify nginx restart"
  debug:
    msg: "Notification: Restart of Nginx has occurred."
    verbosity: 0

